services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e_board
      PGDATA: /pgdata
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - ${KC_POSTGRES_PORT_MAPPING:-5432}:5432
    volumes:
      - ./pgdata:/pgdata

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    command:
      - start
      - --auto-build
      - --db=postgres
      - --hostname-strict-https=false
      - --hostname-strict=false
      - --proxy=edge
      - --http-enabled=true
      - --import-realm
      - --spi-user-profile-legacy-user-profile-read-only-attributes=*_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://postgres:5432/e_board
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8282:8080
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master" ]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s

volumes:
  pgdata:
    driver: local