spring:
  application.name: UsersCRUD

  datasource:
    url: jdbc:postgresql://localhost:5432/e_board
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8081
