openapi: 3.1.0

info:
  title: Модуль приложения eBoard реализующий CRUD-операции для сущности User
  version: 0.0.1

servers:
  - url: http://localhost:8082
    description: адрес сервера
  
paths:

components:
  schemas:
    AdvertDTO:
      title: Объявление
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          description: UUID объявления
        title:
          type: string
          description: Заголовок объявления
        cost:
          type: number
          format: float
        description:
          type: string
          description: Описание объявления
        owner:
          type: object
          schema:
            $ref: '../UsersCRUD/src/main/resources/users-crud-openapi.yaml#/components/schemas/UserDTO'